baseURL = "https://fernandoindesign.github.io/smartfox-blog-hugo/"
title = "SmartFox Blog"
paginate = 5
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"

[minify]
disableXML = true
# minifyOutput = true

[params]
env = "production"
title = "SmartFox"
description = "Blog sobre Growth y Desarrollo Web3"
keywords = [ "Blog", "Growth", "SmartFox", "Crypto" ]
author = "smartfox"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "light"
# disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
# comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

  [params.assets]
  favicon = "favicon.svg"
  favicon16x16 = "favicon.svg"
  favicon32x32 = "favicon.svg"
  apple_touch_icon = "favicon.svg"
  safari_pinned_tab = "favicon.svg"

  [params.label]
  text = "SmartFox Blog"
  icon = "favicon.svg"
  iconHeight = 40

  [params.homeInfoParams]
  Title = "Hola! 👋"
  Content = "Bienvenidos al blog mas pro"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/"

  [[params.socialIcons]]
  name = "telegram"
  url = "https://google.com"

   [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

   [[params.socialIcons]]
  name = "email"
  url = "https://google.com/"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "SmartFox"
name = "smartfox.agency💻"
url = "https://smartfox.agency"
weight = 50
